# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: CI

on: [pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Test
        run: |
          cd app && npm test

      - name: Audit
        run: |
          cd app && npm audit

  build:
    needs: test
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        env:
         IMAGE_TAG: ${{ github.sha }}
        run: |
         docker build -t "$GITHUB_REPOSITORY:$IMAGE_TAG" .


  
